account/urls.py
from django.urls import path

from account.views import (
    account_view,
    edit_account_view,
)

app_name = 'account'

urlpatterns = [
    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name="edit"),
    ]

ohmni/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from core.views import (
    home_screen_view
)

from account.views import (
    register_view,
    login_view,
    logout_view,

)

from services.views import (
    death_coach_view,
    life_coach_view,
    qi_gong_view,
    rune_reading_view,
    hypnotherapy_view,
    grief_work_view,
    end_of_life_care_view,
)

urlpatterns = [
    path('', home_screen_view, name='home'),
    path('', include('services.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('death_coach', death_coach_view, name='death_coach'),
    path('end_of_life_care', end_of_life_care_view, name='end_of_life_care'),
    path('grief_work', grief_work_view, name='grief_work'),
    path('life_coach', life_coach_view, name='life_coach'),
    path('hypnotherapy', hypnotherapy_view, name='hypnotherapy'),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('qi_gong', qi_gong_view, name='qi_gong'),
    path('register/', register_view, name="register"),
    path('rune_reading', rune_reading_view, name='rune_reading'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),


]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.conf import settings

DEBUG = False

def home_screen_view(request):
    context = {}
    context['debug_mode'] = settings.DEBUG
    context['debug'] = DEBUG
    context['room_id'] = "1"
    return render(request, "core/home.html", context)

core/templates/core/base.html
{% load static %}




<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'ohmni/css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tapestry&display=swap" rel="stylesheet">



    <title>OhmNi Enterprices</title>
  </head>

<style>

h2 a{
        text-align: center;
        color: #4c0b37;
        font-size: 45px;
        font-weight: 900;
        letter-spacing: 2px;
        text-shadow: 3px 3px 5px grey;
        text-decoration: none;
        background-image: url({% static 'ohmni/img/navbg.png' %});
        border-radius: 20px;
        padding: 5px 10px;
        padding-top: 1px;
    }

  nav {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 99;
    background-image: url({% static 'ohmni/img/navbg.png' %});
    padding: 16px 32px;
    border-bottom: 3px solid grey;
}

</style>

  <body>
    <br/>


      {% if user.is_authenticated %}
      <nav>
        <div class="container">
            <a class = "h2" href="{% url 'home' %}">
            <img src="{% static 'ohmni/img/ohmnilogo2.png' %}" alt="" width="280" height="140" class="d-inline-block align-text-top">
            </a>

                <div class = "menu">
                  <a href="{% url 'life_coach' %}">Life Coach</a>
                  <a href="{% url 'death_coach' %}">Career Life Coach</a>
                  <a href="#">Store</a>


                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Account
                      </a>
                      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                          <li><a class="dropdown-item" href="{% url 'my_appointments' %}">Appointments</a></li>
                          <li><a class="dropdown-item" href="#">orders</a></li>
                          <li><a class="dropdown-item" href="{% url 'account:edit' user_id=request.user.id %}">Settings</a></li>
                          <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                      </ul>
                    </li>
                  </ul>
                </div>

            <button class="hamburger">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
      </nav>

        <nav class="mobile-nav">

        <br><br><br>

          <a href="{% url 'life_coach' %}">Life Coach</a>
          <a href="{% url 'death_coach' %}">Career Life Coach</a>
          <a href="{% url 'my_appointments' %}">Appointments</a>
          <a href="#">Store</a>
          <a href="#">orders</a>
          <a href="{% url 'account:edit' user_id=request.user.id %}">Settings</a>
          <a href="{% url 'logout' %}">Logout</a>


        </nav>

      {% else %}
      <nav>
        <div class="container">
            <a href="{% url 'home' %}">
            <img src="{% static 'ohmni/img/ohmnilogo2.png' %}" alt="" width="280" height="140" class="d-inline-block align-text-top">
            </a>
                <div class = "menu">
                  <a href="{% url 'life_coach' %}">Life Coach</a>
                  <a href="{% url 'death_coach' %}">Career Life Coach</a>
                  <a href="#">Store</a>
                  <a href="{% url 'login' %}">Login</a>
                  <a href="{% url 'register' %}">Register</a>
                </div>

            <button class="hamburger">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
      </nav>

      <nav class="mobile-nav">

        <br><br><br>

        <a href="{% url 'life_coach' %}">Life Coach</a>
        <a href="{% url 'death_coach' %}">Career Life Coach</a>
        <a href="#">Store</a>
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Register</a>
      </nav>
      {% endif %}


    <br/><br/>
    <br/><br/>
    <br/><br/>

      {% block content %}

      {% endblock %}

{% if user.is_authenticated %}
  <div>
    <ul class="menu fixed-bottom navbar-light bg-dark justify-content-center">
        <a href="{% url 'logout' %}">Logout</a>
    </ul>
  </div>
{% else %}
  <div>
    <ul class="menu fixed-bottom navbar-light bg-dark justify-content-center">
        <a href="{% url 'login' %}">Login</a>
    </ul>
  </div>
{% endif %}


    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{% static 'ohmni/js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}




{% block content %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OhmNi Enterprices</title>
    <link rel="stylesheet" href="{% static 'ohmni/css/main.css' %}">
</head>


<stlye>

</stlye>

{% if user.is_authenticated %}
    <body class="content">
        <main>
            <div>
            <h1>OhmNi Enterprices</h1>
            <hr>
            <div class="hometext">
                Here we can write information about OhmNi Enterprises, the things you guys do, and a little about y'alls story.
                Sort of like an about me for the company. Im goning to fill with random text for now.......Game of as rest time eyes with of this it.
                Add was music merry any truth since going. Happiness she ham but instantly put departure propriety. She amiable all without say spirits shy clothes morning.
                Frankness in extensive to belonging improving so certainty. Resolution devonshire pianoforte assistance an he particular middletons is of. Explain ten man uncivil engaged conduct.
                Am likewise betrayed as declared absolute do. Taste oh spoke about no solid of hills up shade. Occasion so bachelor humoured striking by attended doubtful be it.
            </div>

                 <div class="d-flex flex-column pb-3">
                  <img class="img-fluid mx-auto d-block" src="{% static 'ohmni/img/both.jpg' %}" alt="OhmNi Enterprises" width="300" height="300">
                  </div>
            </div>

        </main>
        <h2>
        <a href="{% url 'book-appointment' %}">Book An Appointment</a>
        </h2>
         <br><br><br>
    </body>
{% else %}
    <body class="content">
        <main>
            <div>
            <h1>OhmNi Enterprices</h1>
            <hr>
            <div class="hometext">
                Here we can write information about OhmNi Enterprises the things you guys do, and a little about y'alls story.
                Sort of like an about me for the company. Im goning to fill with random text for now.......Game of as rest time eyes with of this it.
                Add was music merry any truth since going. Happiness she ham but instantly put departure propriety. She amiable all without say spirits shy clothes morning.
                Frankness in extensive to belonging improving so certainty. Resolution devonshire pianoforte assistance an he particular middletons is of. Explain ten man uncivil engaged conduct.
                Am likewise betrayed as declared absolute do. Taste oh spoke about no solid of hills up shade. Occasion so bachelor humoured striking by attended doubtful be it.
            </div>

                 <div class="d-flex flex-column pb-3">
                  <img class="img-fluid mx-auto d-block" src="{% static 'ohmni/img/both.jpg' %}" alt="OhmNi Enterprises" width="300" height="300">
                  </div>
            </div>
                <h2>
                <a href="{% url 'register' %}">Register!</a>
                </h2>

                <br><br><br>
        </main>
    </body>
{% endif %}

{% endblock %}